Account management rework
HelixLauncher/HelixLauncher pull request #9
Opened 2023-06-28 20:18 UTC by anonymous123-code

- `accounts.helix.json` now uses a json object which contains the account list and the index of the selected instance. *this will break old versions of the file*
- The corresponding struct also stores the path, so it can be saved using a method
- refactored the account management CLI and reworked it to use the new system

2023-06-29 15:40 UTC, Oliver-makes-code approved these changes
lgtm

2023-06-29 16:00 UTC, kb-1000 requested changes
Please rebase rather than merging the main branch in.

2023-06-29 16:18 UTC, anonymous123-code commented
> Please rebase rather than merging the main branch in.

Should I do that for the current PRs or is that for the future?

2023-06-29 16:22 UTC, anonymous123-code commented on helixlauncher-cli/src/main.rs
> +        .await?;
Anyhow errors generally look pretty good:
![grafik](https://github.com/HelixLauncher/HelixLauncher/assets/61744596/f880ecd9-2293-4bfe-bc6b-345d8537703a)

2023-06-29 16:23 UTC, anonymous123-code commented on helixlauncher-cli/src/main.rs
> +use anyhow::{Ok, Result};
No it isnt, I saw it in autocomplete and just assumed it is.

2023-06-29 19:26 UTC, anonymous123-code commented on helixlauncher-core/src/auth/account.rs
> +    pub selected: usize,
Hmm, should I rename it to `selected_uuid`, too?

2023-06-29 19:30 UTC, kb-1000 commented on helixlauncher-core/src/auth/account.rs
> +    pub selected: usize,
Well, if the UUID is the "id" of the account we use, then it would make sense not to, too

2023-06-29 19:32 UTC, kb-1000 commented
> Should I edit the commit history for the current PRs or is that for the future?

I'll just squash merge it when it's ready, you don't need to

2023-06-30 01:13 UTC, kb-1000 requested changes

2023-06-30 01:13 UTC, kb-1000 commented on helixlauncher-core/src/auth/account.rs
> -        account.selected = true
This feature appears to be missing in the new implementation: defaulting to the single account in the list if there is only one (though that should probably be done in the place it's used in, if the selected default is `None`)

2023-06-30 19:50 UTC, kb-1000 approved these changes
There's still a few nitpicks but I can change those post-merge.
Otherwise, LGTM.

2023-07-09 20:58 UTC, anonymous123-code commented
I now fixed the error when saving a deserialized, and added a corresponding test case.

2023-07-21 19:24 UTC, merged